ServerEvents.recipes(event => {
    event.recipes.mekanism.crushing('exdeorum:crushed_netherrack', 'minecraft:netherrack');
    event.recipes.mekanism.crushing('minecraft:red_sand', 'minecraft:netherrack');
    event.recipes.mekanism.crushing('exdeorum:crushed_end_stone', 'minecraft:end_stone');
    event.recipes.mekanism.crushing('exdeorum:crushed_deepslate', 'minecraft:deepslate');
    event.recipes.mekanism.crushing('exdeorum:crushed_deepslate', 'minecraft:cobbled_deepslate');
    event.recipes.mekanism.crushing('exdeorum:crushed_blackstone', 'minecraft:blackstone');
    event.recipes.mekanism.crushing(Item.of('exdeorum:crushed_netherrack', 9), 'exdeorum:compressed_netherrack');
    event.recipes.mekanism.crushing(Item.of('exdeorum:crushed_end_stone', 9), 'exdeorum:compressed_end_stone');
    event.recipes.mekanism.crushing(Item.of('exdeorum:crushed_deepslate', 9), 'exdeorum:compressed_deepslate');
    event.recipes.mekanism.crushing(Item.of('exdeorum:crushed_blackstone', 9), 'exdeorum:compressed_blackstone');
    event.recipes.mekanism.crushing(Item.of('exdeorum:dust', 9), 'exdeorum:compressed_sand');
    event.recipes.mekanism.crushing(Item.of('exdeorum:dust', 9), 'exdeorum:compressed_red_sand');
    event.recipes.mekanism.crushing(Item.of('exdeorum:crushed_deepslate', 9), 'exdeorum:compressed_cobbled_deepslate');
    event.recipes.mekanism.crushing(Item.of('minecraft:gravel', 9), 'exdeorum:compressed_cobblestone');
    event.recipes.mekanism.crushing(Item.of('minecraft:gravel', 9), 'exdeorum:compressed_diorite');
    event.recipes.mekanism.crushing(Item.of('minecraft:gravel', 9), 'exdeorum:compressed_granite');
    event.recipes.mekanism.crushing(Item.of('minecraft:gravel', 9), 'exdeorum:compressed_andesite');
    event.recipes.mekanism.crushing(Item.of('minecraft:sand', 9), 'exdeorum:compressed_gravel');
    event.recipes.mekanism.crushing(Item.of('minecraft:red_sand', 9), 'exdeorum:compressed_netherrack');
    event.recipes.mekanism.crushing(Item.of('ae2lt:firmament_dust'), 'naturesaura:sky_ingot');
});