StartupEvents.registry('fluid', event => {
    event.create('liquid_gold')
        .displayName('液态金')
        .stillTexture('kubejs:block/liquid_gold_still')
        .flowingTexture('kubejs:block/liquid_gold_flow')
        .noBlock()

    event.create('liquid_redstone')
        .displayName('液态红石')
        .stillTexture('kubejs:block/liquid_redstone_still')
        .flowingTexture('kubejs:block/liquid_redstone_flow')
        .noBlock()

    event.create('liquid_diamond')
        .displayName('液态钻石')
        .stillTexture('kubejs:block/liquid_diamond_still')
        .flowingTexture('kubejs:block/liquid_diamond_flow')
        .noBlock()

    event.create('liquid_refined_obsidian')
        .displayName('液态强化黑曜石')
        .stillTexture('kubejs:block/liquid_refined_obsidian_still')
        .flowingTexture('kubejs:block/liquid_refined_obsidian_flow')
        .noBlock()

    event.create('antimatter')
        .displayName('反物质')
        .stillTexture('kubejs:block/antimatter_gas_still')
        .flowingTexture('kubejs:block/antimatter_gas_flow')
        .noBlock()
})