ServerEvents.recipes(event => {
    event.recipes.casting.solidifier('exdeorum:compressed_sand', '900x casting:molten_coal', 'geore:budding_coal')
    event.recipes.casting.solidifier('exdeorum:compressed_sand', '900x casting:molten_copper', 'geore:budding_copper')
    event.recipes.casting.solidifier('exdeorum:compressed_sand', '900x casting:molten_diamond', 'geore:budding_diamond')
    event.recipes.casting.solidifier('exdeorum:compressed_sand', '900x casting:molten_emerald', 'geore:budding_emerald')
    event.recipes.casting.solidifier('exdeorum:compressed_sand', '900x casting:molten_gold', 'geore:budding_gold')
    event.recipes.casting.solidifier('exdeorum:compressed_sand', '900x casting:molten_iron', 'geore:budding_iron')
    event.recipes.casting.solidifier('exdeorum:compressed_sand', '900x casting:molten_lapis', 'geore:budding_lapis')
    event.recipes.casting.solidifier('exdeorum:compressed_sand', '900x casting:molten_quartz', 'geore:budding_quartz')
    event.recipes.casting.solidifier('exdeorum:compressed_sand', '900x casting:molten_redstone', 'geore:budding_redstone')
    event.recipes.casting.solidifier('exdeorum:compressed_sand', '900x casting:molten_debris', 'geore:budding_ancient_debris')
    event.recipes.casting.solidifier('exdeorum:compressed_sand', '900x casting:molten_ruby', 'geore:budding_ruby')
    event.recipes.casting.solidifier('exdeorum:compressed_sand', '900x casting:molten_sapphire', 'geore:budding_sapphire')
    event.recipes.casting.solidifier('exdeorum:compressed_sand', '900x casting:molten_zinc', 'geore:budding_zinc')
    event.recipes.casting.solidifier('exdeorum:compressed_sand', '900x casting:molten_aluminum', 'geore:budding_aluminum')
    event.recipes.casting.solidifier('exdeorum:compressed_sand', '900x casting:molten_lead', 'geore:budding_lead')
    event.recipes.casting.solidifier('exdeorum:compressed_sand', '900x casting:molten_nickel', 'geore:budding_nickel')
    event.recipes.casting.solidifier('exdeorum:compressed_sand', '900x casting:molten_osmium', 'geore:budding_osmium')
    event.recipes.casting.solidifier('exdeorum:compressed_sand', '900x casting:molten_platinum', 'geore:budding_platinum')
    event.recipes.casting.solidifier('exdeorum:compressed_sand', '900x casting:molten_silver', 'geore:budding_silver')
    event.recipes.casting.solidifier('exdeorum:compressed_sand', '900x casting:molten_tin', 'geore:budding_tin')
    event.recipes.casting.solidifier('exdeorum:compressed_sand', '900x casting:molten_uranium', 'geore:budding_uranium')
})