#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Mar 19 23:50:16 CST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
