FixDEDislocatorThreadBug = true
FixBrandonsCoreNullptr = true
FixMMSMSwimInAir = true
FixMMSMEnergyShieldAntiDieBug = true
FixMMSM = true
#Allowed Values: DISABLED, PHASE_ONLY, ALWAYS
FixPhaseCamera = "PHASE_ONLY"
FixDEHUDRenderBug = true
FixDECuriosOrderBug = true
FixPlayerShellsDiePriority = true
#Allowed Values: DISABLED, DE_ONLY, ALL
FixAECraftNBT = "DE_ONLY"
# Default: 3
# Range: > -2147483648
CommandConfigPremissionLevel = 3
# Default: 4
# Range: > -2147483648
CommandToolsPermissionLevel = 4
FixPackagedDEDoesntUseInput = true
#Allowed Values: DISABLED, TIMEOUT, NO_UPLOAD
FixObNetStuck = "NO_UPLOAD"
# Default: 5000
# Range: > 0
ObservableTimeoutTime = 5000
