soul_extract_returns = false
# Default: 10
# Range: 0 ~ 160
frequency_essence_collect = 10

[factor]
	# Default: 10
	# Range: 0 ~ 128
	aureal = 10
	# Default: 10
	# Range: 0 ~ 128
	blood = 10
	# Default: 10
	# Range: 0 ~ 128
	souls = 10
	# Default: 10
	# Range: 0 ~ 128
	experience = 10
