// jei_hide/hide_lowtier_generators.js
// ─────────────────────────────────────────────────────────
// 来自原 client_scripts/hide_items.js
// 在 JEI/REI/EMI 中隐藏 ~120 个低阶/低性价比发电机（powah、工业先锋、mekanismgenerators、
// ifmup、mekmm、productivebees、justdirethings 等跨 20+ mod）。
// 玩家可手动在客户端 JEI 设置中恢复。
// ─────────────────────────────────────────────────────────

const ITEMS_TO_HIDE = [
    "powah:furnator_starter",
    "powah:furnator_basic",
    "powah:furnator_hardened",
    "powah:furnator_blazing",
    "powah:furnator_niotic",
    "powah:furnator_spirited",
    "powah:furnator_nitro",
    "powah:magmator_starter",
    "powah:magmator_basic",
    "powah:magmator_hardened",
    "powah:magmator_blazing",
    "powah:magmator_niotic",
    "powah:magmator_spirited",
    "powah:magmator_nitro",
    "powah:thermo_generator_starter",
    "powah:thermo_generator_basic",
    "powah:thermo_generator_hardened",
    "powah:thermo_generator_blazing",
    "powah:thermo_generator_niotic",
    "powah:thermo_generator_spirited",
    "powah:thermo_generator_nitro",
    "powah:solar_panel_starter",
    "powah:solar_panel_basic",
    "powah:solar_panel_hardened",
    "powah:solar_panel_blazing",
    "powah:solar_panel_niotic",
    "powah:solar_panel_spirited",
    "powah:solar_panel_nitro",
    "industrialforegoing:pitiful_generator",
    "enderio_evolution:simple_stirling_generator",
    "enderio_evolution:basic_infinity_generator",
    "enderio_evolution:crystalline_infinity_generator",
    "enderio_evolution:stellar_infinity_generator",
    "extendedae_plus:infinity_biginteger_cell",
    "mekanismgenerators:wind_generator",
    "enderio:stirling_generator",
    "industrialforegoing:mycelial_furnace",
    "industrialforegoing:mycelial_pink",
    "industrialforegoing:mycelial_frosty",
    "industrialforegoing:biofuel_generator",
    "create_connected:fluid_vessel",
    "ironfurnaces:augment_generator",
    "extendedae_plus:entity_speed_card",
    "mekanismgenerators:bio_generator",
    "integrateddynamics:coal_generator",
    "productivebees:honey_generator",
    "actuallyadditions:oil_generator",
    "actuallyadditions:heat_collector",
    "actuallyadditions:coal_generator",
    "actuallyadditions:leaf_generator",
    "ironfurnaces:upgrade_allthemodium",
    "mekmm:large_gas_burning_generator",
    "mekmm:large_heat_generator",
    "mekanismgenerators:module_geothermal_generator_unit",
    "appliedcreate:kinetic_energy_acceptor",
    "draconicevolution:generator",
    "immersiveengineering:thermoelectric_generator",
    "mekanismgenerators:gas_burning_generator",
    "industrialforegoing:mycelial_reactor",
    "industrialforegoing:mycelial_slimey",
    "industrialforegoing:mycelial_culinary",
    "industrialforegoing:mycelial_potion",
    "industrialforegoing:mycelial_disenchantment",
    "industrialforegoing:mycelial_ender",
    "industrialforegoing:mycelial_explosive",
    "industrialforegoing:mycelial_halitosis",
    "industrialforegoing:mycelial_magma",
    "industrialforegoing:mycelial_netherstar",
    "industrialforegoing:mycelial_death",
    "industrialforegoing:mycelial_rocket",
    "industrialforegoing:mycelial_crimed",
    "industrialforegoing:mycelial_meatallurgic",
    "mekanismgenerators:heat_generator",
    "ifmup:processing_addon_tier_8",
    "ifmup:processing_addon_tier_7",
    "ifmup:efficiency_addon_tier_8",
    "ifmup:efficiency_addon_tier_7",
    "ifmup:speed_addon_tier_8",
    "ifmup:speed_addon_tier_7",
    "ifmup:range_addon_tier_12",
    "ifmup:range_addon_tier_13",
    "ifmup:range_addon_tier_14",
    "ifmup:range_addon_tier_15",
    "ifmup:range_addon_tier_16",
    "ifmup:range_addon_tier_17",
    "ifmup:range_addon_tier_18",
    "ifmup:range_addon_tier_19",
    "ifmup:range_addon_tier_20",
    "ifmup:range_addon_tier_21",
    "ifmup:range_addon_tier_22",
    "ifmup:range_addon_tier_23",
    "ifmup:range_addon_tier_24",
    "ifmup:range_addon_tier_25",
    "ifmup:range_addon_tier_26",
    "ifmup:range_addon_tier_27",
    "ifmup:range_addon_tier_28",
    "ifmup:range_addon_tier_29",
    "ifmup:range_addon_tier_30",
    "ifmup:range_addon_tier_31",
    "ifmup:range_addon_tier_47",
    "ifmup:range_addon_tier_63",
    "ifmup:range_addon_tier_71",
    "ifmup:range_addon_tier_79",
    "ifmup:nether_star_gear",
    "ifmup:star_ether_alloy_gear",
    "mysticalagriculture:neutronium_seeds",
    "mysticalagriculture:neutronium_essence",
    "mysticalagriculture:awakened_draconium_seeds",
    "mysticalagriculture:awakened_draconium_essence",
    "mysticalagriculture:dragon_egg_seeds",
    "mysticalagriculture:dragon_egg_essence",
    "ifmup:shadow_plate",
    "ifmup:unknown_magic_plate",
    "ifmup:shadow_rose_plate",
    "ifmup:star_ether_alloy_plate",
    "sophisticatedstorage:stack_upgrade_omega_tier",
    "sophisticatedbackpacks:stack_upgrade_omega_tier",
    "productivebees:advanced_quark_blossom_beehive",
    "productivebees:expansion_box_quark_blossom",
    "productivebees:advanced_quark_azalea_beehive",
    "productivebees:expansion_box_quark_azalea",
    "justdirethings:generatort1",
    "justdirethings:generatorfluidt1",
    "justdirethings:pocket_generator",
    "mysticalagriculture:copper_alloy_seeds" ,
    "mysticalagriculture:copper_alloy_essence"
];

RecipeViewerEvents.removeEntries('item', event => {
    for (const id of ITEMS_TO_HIDE) {
        event.remove(id);
    }
    console.info(`[hide_items] Hidden ${ITEMS_TO_HIDE.length} items from JEI`);
});
